### PR TITLE
Added testimonial page with option to add more reviews, closes PR #117

### LINKED ISSUE #117: Adding testimonial page with your reviews, with option to add more reviews
# Issue Template

## Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System:
* SDK version:
* Toolchain version:

## Expected Behavior

People can add their reviews about our webapp

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

### PR DESCRIPTION
**Pull request by debsouryadatta**
## Description
Now you can see the testimonials given by all the people on the testimonials page, you can also add your review onto it.

Fixes #117 

## Type of change
Adding a new feature -> Testimonials page with Firebase integration

### CODE REVIEW

**Comment by Arnabdaz** [comment]
@debsouryadatta nice work ... but some changes are needed ... 
#### todo:
testimonials page should be accessible for non logged in users where they should not be able to add testimonial and when logged in they can provide testimonial ...

#### improvements:
 rather than taking their name using input field take their name from account ... 
 in the db part keep their name , account id and testimonial they write ... 
 so that people can not spam in the testimonial and we check if testimonial from the user already exist ... if not then only we allow him to write a new one 
 finally, if he already wrote testimonial earlier when he tries to write new one you load the old testimonial he wrote form db and let him edit that.
 
 the todo part you need to do for the pr to be merged and  the improvement part you can do if it does not seem too hard for you ... else you can create a new issue for that part

**Comment by debsouryadatta** [comment]
@Arnabdaz Thanks for the clear cut description, will do that ASAP!

**Comment by debsouryadatta** [comment]
Hii @Arnabdaz  , Done with the todo part, will create an issue for the improvement part, till then please review it!

**Review by Arnabdaz — APPROVED** [review]
LGTM :+1: nice work :rocket: 

you can create a new issue for the improvements

**Comment by debsouryadatta** [comment]
@Arnabdaz I have a doubt regarding the improvement part, so what if the user has not updated his name in his profile, should I give an alert like "Update your name on the profile first".

**Comment by Arnabdaz** [comment]
> @Arnabdaz I have a doubt regarding the improvement part, so what if the user has not updated his name in his profile, should I give an alert like "Update your name on the profile first".

Yes

**Pull request merged**
