### PR TITLE
Add Copyright Year to Be Dynamic

### PR DESCRIPTION
**Pull request by Shubham29012001**
issue No: #24 

Made Copyright Section to get current year dynamically using getFullYear() from Date()

image

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
nice thanks a ton... Lgtm ✅

**Comment by Shubham29012001** [comment]
Fixes No: #24

**Comment by KendallDoesCoding** [comment]
> Fixes No: #24

Nono, you need to put in the description

> issue No: https://github.com/agamjotsingh18/pollitup/issues/24

Made Copyright Section to get current year dynamically using getFullYear() from Date()

Here, instead of **issue** edit to to **fixes #24**

**Comment by KendallDoesCoding** [comment]
> > Fixes No: #24
> 
> Nono, you need to put in the description
> 
> > issue No: #24
> 
> Made Copyright Section to get current year dynamically using getFullYear() from Date()
> 
> Here, instead of **issue** edit to to **fixes #24**

If your new to open source and can't understand how to do it though. We can totally understand that... @agamjotsingh18 Please link this PR to the issue, you can either go to the issue and link the PR or edit the description and do it, only you or Shubham can do it :)

**Comment by KendallDoesCoding** [comment]
Thanks a lot @Shubham29012001 !!

**Pull request merged**
