### PR TITLE
Fixed the issue on the poll info page with the Author profile link, closes #253

### LINKED ISSUE #253: Issue on the poll info page with the Author profile link
### Description

When user click on Author(Click to view profile) on the Poll info page, it gets redirected to the user’s own profile rather than the author’s profile.

### Screenshots

Screenshot (329)
Screenshot (330)

### PR DESCRIPTION
**Pull request by debsouryadatta**
## Description

Now when user will click on Author(Click to view profile) on the Poll info page, it will get redirected to the profile of the author rather than user's own profile.

Fixes #253 

## Type of change
Change in the implementation of firebase user data

### CODE REVIEW

**Comment by debsouryadatta** [comment]
Hey @Arnabdaz 👋, can you please review this PR.

**Comment by Arnabdaz** [comment]
> Hey @Arnabdaz wave, can you please review this PR.

when user is not logged in and clicks on view profile from a poll page it loads a blank profile page can you fix that ?

**Comment by debsouryadatta** [comment]
@Arnabdaz Okay, looking into it👀

**Comment by debsouryadatta** [comment]
Hey @Arnabdaz , I think its good to go now!✌️

**Review by Arnabdaz — APPROVED** [review]

**Pull request merged**
