### PR TITLE
add pages corresponding to password reset option

### PR DESCRIPTION
**Pull request by AmoghCreator**
Screenshot from 2023-05-24 09-58-41

Screenshot from 2023-05-24 09-58-57

## Description

Added two new pages for the Forget Password feature 
1. Page to request email
2. Confirmation page to notify user of the email
 
Also, added the corresponding routes inside the App.js

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Future Scope 

1. Some contextual improvements to be made
2. Implement firebase to complete the password reset process

### CODE REVIEW

**Comment by Arnabdaz** [comment]
@AmoghCreator could you remove <span>Enter the Email associated with your account </span> from the emailsent.jsx page

**Comment by Arnabdaz** [comment]
> @Arnabdaz Sure, do you want me to replace it with something or just remove it ??

you can just remove it or you can replace it with a green tick mark svg or animation i guess

**Comment by AmoghCreator** [comment]
@Arnabdaz Please Review :-)

**Comment by Arnabdaz** [comment]
> @Arnabdaz Please Review :-)

code looks fine but did you consider the cases when the email doesn't exist or reset password email sending is unsuccessful? or you plan to add those later while implementing the reset mechanism ?

**Comment by AmoghCreator** [comment]
> > @Arnabdaz Please Review :-)
> 
> code looks fine but did you consider the cases when the email is not registered or reset password email sending is unsuccessful? or you plan to add those later while implementing the reset mechanism ?

Yes, I plan to add them later, with the complete implementation.

**Review by Arnabdaz — APPROVED** [review]

**Pull request merged**
