### PR TITLE
Connect Create Pole form to Firebase Backend, closes pr #112

### LINKED ISSUE #112: Connect Create Pole form to Firebase Backend
## Expected Behavior

The data entered by users in poles should be sent to Firestore with all the necessary parameters against the username. 

## Current Behavior
When we are creating a form now the data isn't being posted on Firestore, and hence cannot be retrieve it to display the poll on the Dashboard.

### PR DESCRIPTION
**Pull request by debsouryadatta**
# Pull Request Template

## Description
Connected the create pole form to the firebase backend, now on all the polls created by the user will be stored in the firestore database

Fixes #112 

## Type of change
Connection to Database.

### CODE REVIEW

**Comment by Arnabdaz** [comment]
@debsouryadatta can you add option delete a poll from the dashboard?

**Comment by Arnabdaz** [comment]
polls are showing up both on dashboard and discover page also in the map ... so if you could just add the delete functionality it would be totally usable ... you can create a new issue for the same.

**Comment by SoundaryaKoutharapu** [comment]
I've seen the deployment, Polls are visible in Dashboard, but they are not visible in Profile section.

**Comment by debsouryadatta** [comment]
@Arnabdaz So should create an issue and start working for the delete functionality?

**Comment by Arnabdaz** [comment]
> @Arnabdaz So should create an issue and start working for the delete functionality?

Yes go on

**Comment by debsouryadatta** [comment]
> > @Arnabdaz So should create an issue and start working for the delete functionality?
> 
> Yes go on

Till then can you merge this PR✌️

**Comment by agamjotsingh18** [comment]
@Arnabdaz looks good, you can merge it, assign the specific labels

**Comment by debsouryadatta** [comment]
Hello @Arnabdaz , can you label the level of the PR.

**Pull request merged**
