### PR TITLE
Fixed the problem of showing null in copied link of the polls, fixes #275

### LINKED ISSUE #275: The links of the polls(which can be copied) on the Discover page are showing null
### Description

After copying the links of the polls, when we visit the copied link, the link shows null in its route.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by debsouryadatta**
## Description
Now the copied links of the polls are not showing null, you can copy the link and share the link with others having no issue.

Fixes #275 

## Type of change
Change in the backend code of data fetching

### CODE REVIEW

**Comment by debsouryadatta** [comment]
Hey @Arnabdaz , fixed the issue #275 , please review it.
And one more thing, I don't know why the previous 3 commits came up automatically, can you help me out with this.

**Comment by Arnabdaz** [comment]
This is because you created a branch out of the old branch, rather than the main branch after the merging of last issue, pulling those changes

**Review by Arnabdaz — APPROVED** [review]
LGTM

**Comment by Arnabdaz** [comment]
I am please try to create the new branches form main branch as it might include unwanted changes / commits / create merge conflict etc

**Comment by debsouryadatta** [comment]
> I am please try to create the new branches form main branch as it might include unwanted changes / commits / create merge conflict etc

But I have made the new branch from the main branch itself

**Comment by debsouryadatta** [comment]
Okay let me have a research, I will ask if I face any problem✌️

**Comment by Arnabdaz** [comment]
> > I am please try to create the new branches form main branch as it might include unwanted changes / commits / create merge conflict etc
> 
> But I have made the new branch from the main branch itself

try pulling the new changes form the main branch it should fix the issue

**Comment by debsouryadatta** [comment]
> > > I am please try to create the new branches form main branch as it might include unwanted changes / commits / create merge conflict etc
> > 
> > But I have made the new branch from the main branch itself
> 
> try pulling the new changes form the main branch it should fix the issue

Okay thanks 🙌

**Pull request merged**
