### PR TITLE
Add Captcha Verification

### LINKED ISSUE #194: [FEATURE] Add Captcha in Register Form
### Description

I will like to add Captcha verification in the register form of the website.

### Screenshots

image
Somewhere below the confirm section i wanna add the captcha

### PR DESCRIPTION
**Pull request by Manice18**
# Pull Request Template

## Description

Add a Captcha verification and add it to the Register form so that it prevents bots from signing up and differentiates it from actual human users

Fixes #194 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

##Screenshot
image

##Working video:

https://github.com/agamjotsingh18/pollitup/assets/91601706/843d6209-1e88-4bbd-b829-2263ef1bcf78

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Manice18** [comment]
@Arnabdaz can you check and tell ?

**Comment by Arnabdaz** [comment]
> @Arnabdaz can you check and tell ?

Hi @Manice18 you implemented the captcha really nicely , but there are some things I should tell you:

1. the way you implemented the captcha by adding blur on the input field would really make it hard for robots to scan the text but so it would do for humans specially visually impared peoples. 
anyways this can be solved easily with a audio captcha option or some other accessability options

2, As you are using a input filed to show the capcha image the value can easily be read by a bot which defeats the whole purpose of having captcha 
image

**Comment by Manice18** [comment]
> Anyways lets come to solution: for hiding the text from html dom you use textarea to display the without making it available in the dom make sure to add the text as:
> 
> ```
> <textarea id="someId"></textarea>
> document.getElementById('someId').value = [captcha value]
> ```
> 
> and for the visually impared people part we can come up with some other method like audio captcha which can be implemented with a new issue and pr

simply you are telling me to remove the input field to display the captcha, and instead add textarea to display it and use dom to show, update the captcha , am i correct ? @Arnabdaz

**Comment by Arnabdaz** [comment]
> > Anyways lets come to solution: for hiding the text from html dom you use textarea to display the without making it available in the dom make sure to add the text as:
> > ```
> > <textarea id="someId"></textarea>
> > document.getElementById('someId').value = [captcha value]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and for the visually impared people part we can come up with some other method like audio captcha which can be implemented with a new issue and pr
> 
> simply you are telling me to remove the input field to display the captcha, and instead add textarea to display it and use dom to show, update the captcha , am i correct ? @Arnabdaz

yep so that the captcha is not visible in the html

**Comment by Manice18** [comment]
@Arnabdaz i am done with all the changes but i am having one problem which is: i am not able to adjust the height of the textarea
image

**Comment by Arnabdaz** [comment]
> @Arnabdaz i am done with all the changes but i am having one problem which is: i am not able to adjust the height of the textarea. I used the chakra ui Textarea image

can you push the changes ?

**Comment by Manice18** [comment]
ya wait

**Comment by Manice18** [comment]
@Arnabdaz can you check now, the latest commit that i made

**Comment by Arnabdaz** [comment]
> @Arnabdaz can you check now, the latest commit that i made

cool just add rows property to the textarea element `rows="1"` should make it look like input also increase its width because when lot of wide characters come they break in two lines so like make it like 10 or 11 rem wide ( 1rem = 16px by default so if you are setting in px just use 160 px or 170px would be enough width for 6 characters)
also along with this fix make sure the text inside is not selectable 
you can refer to https://code-boxx.com/make-html-text-unselectable/ or if possible comeup with a better solution

**Comment by Manice18** [comment]
@Arnabdaz done 
image

**Comment by Manice18** [comment]
all working now @Arnabdaz

**Comment by Arnabdaz** [comment]
could you remove the selection of the text else one can easily drag and drop the captcha text or copy paste it
[Updated: simulator api endpoints implemented in /api/v1/projects enpoint](https://github.com/CircuitVerse/CircuitVerse/pull/3861)

**Comment by Arnabdaz** [comment]
could you remove the selection of the text else one can easily drag and drop the captcha text or copy paste it

[Screencast from 2023-07-01 22-58-18.webm](https://github.com/agamjotsingh18/pollitup/assets/96580571/2568f73e-50a6-4238-9919-3406ef892026)

**Comment by Manice18** [comment]
@Arnabdaz  i already did that , i dont know why it's happenning in you case 
image

https://github.com/agamjotsingh18/pollitup/assets/91601706/588665ae-7e11-4e0e-9ce5-55d4a4e9328d


should i add unselectable='on' ?

**Comment by Arnabdaz** [comment]
> @Arnabdaz i already did that , i dont know why it's happenning in you case image
> 
>  test1.mp4 
> should i add unselectable='on' ?

yah you can

**Comment by Manice18** [comment]
@Arnabdaz made the change

**Review by Arnabdaz — APPROVED** [review]
LGTM :+1: nice work :rocket:

**Comment by Arnabdaz** [comment]
@Manice18 if you have another issue to work on ping me on the issue page to be assigned or create a new one and get assigned

**Comment by Manice18** [comment]
> @Manice18 if you have another issue to work on ping me on the issue page to be assigned or create a new one and get assigned

Ok will look into something.

**Pull request merged**
