### PR TITLE
Added - delete poll functionality on dashboard pr #149

### LINKED ISSUE #149: [FEATURE] Add Delete Poll functionality on the Dashboard.
## Expected Behavior
There will be a delete poll option on the dashboard along with the polls

## Current Behavior
The polls on the dashboard don't have any options to be deleted.

I want to work on this issue, Please label and assign it to me.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by debsouryadatta**
## Description

Added the delete poll functionality, now you can delete your created polls from your dashboard.

Fixes #149 

## Type of change

UI change + backend database change

### CODE REVIEW

**Comment by Arnabdaz** [comment]
@debsouryadatta 
image
delete pole option should not be available in the discover page

**Comment by debsouryadatta** [comment]
> @debsouryadatta image delete pole option should not be available in the discover page

Okay, working on it👍

**Comment by debsouryadatta** [comment]
@Arnabdaz I have modified the changes, is that good to go, please review it!!

**Comment by Arnabdaz** [comment]
@debsouryadatta remove the package-lock.json from the commit

**Comment by debsouryadatta** [comment]
@Arnabdaz Done, I have removed👍

**Review by Arnabdaz — APPROVED** [review]
LGTM :+1: 
nice work @debsouryadatta :clap:

**Comment by debsouryadatta** [comment]
> LGTM +1 nice work @debsouryadatta clap

Thanks mann!
Gonna continue contributing, 
Can you just label the PR

**Comment by debsouryadatta** [comment]
Hello @Arnabdaz  , can you label the level of the PR.

**Pull request merged**
