### PR TITLE
Add Share Poll via Link Feature

### LINKED ISSUE #161: [FEATURE] Want to add functionality to share the poll via link.
### Description

Till now, there's no way to share the poll using a link. It would be convenient for the user to share the poll via a link so that the poll grasps maximum attention. So, I wanted to add a feature to generate a link for sharing the poll.

Can you please assign this issue to me as a part of GSSOC'23?

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kartikjoshi267**
## Description
This PR adds a share poll via link feature.
- I have added a `Copy Link` option for each poll to copy the link. Link is of the route `/poll/:id`.
- I have modified the poll results page for the non-owners to view the `Submit your response` button when visiting the page through above copied link.
- Also, until you do not submit a response, responses will not be visible to the user under the `Responses` section.
- When the user clicks on the `Submit your Response`, the `PollPopup` modal opens but no `View Poll Results` appears as we are on the same page.

Fixes #161 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by kartikjoshi267** [comment]
Please take a look and if any changes are required, please suggest

**Review by Arnabdaz — APPROVED** [review]
LGTM :+1: , good work !

**Comment by kartikjoshi267** [comment]
@Arnabdaz Can you please add `gssoc23` and `level2` labels to this PR?

**Comment by Arnabdaz** [comment]
> > > Can you please change the labels from `GSSoC23` and `Level2` to `gssoc23` and `level2`? @Arnabdaz
> > 
> > 
> > what do you mean ?
> 
> Actually the labels that make the PRs count towards the score of a GSSOC candidate are in lowercase like `gssoc23` and `level2` and since you have marked the labels in uppercase, they are not counting towards my score. So, can you please change them?

i Do not think there is such thing .. last year also same format was used 
@agamjotsingh18 needs to confirm for the tags to be changed

**Pull request merged**
