### PR TITLE
Correction in DISCOVER page

### PR DESCRIPTION
**Pull request by marshadkhn**
Hey @Arnabdaz, I corrected the drop down and search button in discover page
Issue number - #217

I aligned the button named as `By Pole Name` and makes the `Search button` as the input in which it is placed as you said### 

### **Previous:**
image

### **My changes:**
image

### CODE REVIEW

**Comment by marshadkhn** [comment]
@Arnabdaz

**Comment by Arnabdaz** [comment]
> @Arnabdaz

nice work just one change can you connect the `by poll name` and `search bar` together so that they look like are continuous

**Comment by marshadkhn** [comment]
I did but they are looking odd
I'll send you a PR today
Just look if it's look good then it's OK

**Comment by Arnabdaz** [comment]
> I did but they are looking odd I'll send you a PR today Just look if it's look good then it's OK

no need to send the pr just send a screen shot if it looks bad we can merge as it is now else you can push the changes and we merge them

**Comment by marshadkhn** [comment]
OK

**Comment by Arnabdaz** [comment]
> image
> 
> **Will look like this** **Should I commit this change and send you a PR?**

cool go ahead

**Comment by marshadkhn** [comment]
OK

**Comment by Arnabdaz** [comment]
> Check the PR - #247

closing this pr and continuing on #247

**Pull request closed without merging**
