### PR TITLE
stick navbar to top

### PR DESCRIPTION
**Pull request by An525ish**
# Pull Request Template

## Description

Made the navbar sticky to top while scrolling

Fixes https://github.com/agamjotsingh18/pollitup/issues/88

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Arnabdaz** [comment]
also change your prettier confing to single quotes instead of double quotes 
as in https://stackoverflow.com/questions/48864985/vscode-single-to-double-quote-automatic-replace

**Comment by An525ish** [comment]
> also change your prettier confing to single quotes instead of double quotes as in https://stackoverflow.com/questions/48864985/vscode-single-to-double-quote-automatic-replace

it's done

**Comment by An525ish** [comment]
> @An525ish nice work but you also included the package.json and package-lock.json in the pr ... add those files in .gitignore and create a new pr ... also in the pr description `Fixes # (issue)` add your issue like Fixes #81 ... ping me once you do the changes for further followup

I have made all the suggested changes...kindly merge it

**Comment by An525ish** [comment]
> ok you need to remove the package.json and package-lock.json from the commits and also .gitignore should not be in the commit so what you should do is only add the navbar.js file in your commit you can do it during adding files to staging area before commit ... so instead of `git add .` you do `git add navbar.js`
> 
> and for the prettier part it seems the jsx uses dobule quotes and js part uses single quotes so you can update your prettier config file as
> 
> test it to see if it is working correctly.
> 
> ```
> {
>   "overrides": [
>     {
>       "files": "*.js",
>       "options": {
>         "singleQuote": true
>       }
>     },
>     {
>       "files": "*.jsx",
>       "options": {
>         "jsxSingleQuote": false
>       }
>     }
>   ]
> }
> ``` I just checked for both the case and it's working completely fine

**Comment by An525ish** [comment]
> ok you need to remove the package.json and package-lock.json from the commits and also .gitignore should not be in the commit so what you should do is only add the navbar.js file in your commit you can do it during adding files to staging area before commit ... so instead of `git add .` you do `git add navbar.js`
> 
> and for the prettier part it seems the jsx uses dobule quotes and js part uses single quotes so you can update your prettier config file as
> 
> test it to see if it is working correctly.
> 
> ```
> {
>   "overrides": [
>     {
>       "files": "*.js",
>       "options": {
>         "singleQuote": true
>       }
>     },
>     {
>       "files": "*.jsx",
>       "options": {
>         "jsxSingleQuote": false
>       }
>     }
>   ]
> }
> ```

Sir , I have already pushed it to the git repo so is there any command to undo that ?

**Comment by An525ish** [comment]
> 

okkay sir

**Pull request closed without merging**
