### PR TITLE
Fixed Profile page, edit section, poll section, etc, closes pr #163

### LINKED ISSUE #163: Fix profile edit section create a new page for editing profile and the current profile page should be for sharing profile
### Current issue:

1. the profile page serves as both edit and profile display page users 
2. the edit profile does not work 
3. profile picture does not upload 
4. polls are not visible in the profile page

### expected behaviour:

1. profile page and profile edit page should be separate 
2. profile edit (such as name change / description changing ) should work
3. User created polls should show up in their profile
4. uploading /updating profile picture should work 

#### Note: on updating profile picture the old profile picture should be deleted from the database
<br>

### `$ Open to all gssoc 23 contributors`

### PR DESCRIPTION
**Pull request by debsouryadatta**
## Description
Now users can easily update their profile picture, name, etc and also the polls created by the users are visible in the profile page itself.

Fixes #163 

## Type of change
Both backend + frontend changes

### CODE REVIEW

**Comment by debsouryadatta** [comment]
Hey @Arnabdaz , can you please review it!!

**Review by Arnabdaz — CHANGES_REQUESTED** [review]
image
can you align the text with the title for now maybe in future we can update the ui for this.

**Comment by debsouryadatta** [comment]
> image can you align the text with the title for now maybe in future we can update the ui for this.

Updated, please have a look!

**Review by Arnabdaz — APPROVED** [review]
LGTM 👍 Nice work 🚀

**Pull request merged**
