### PR TITLE
Added, share profile to other apps feature!

### LINKED ISSUE #235: [FEATURE]  Share your profile to other apps.
### Description

- Now the share button in the profile only copies your profile's URL to a clipboard, and then you manually have to share it with other apps.
- What if we can share with other desired apps there itself using a pop-up card? It would be a wonderful user experience.
- This can be done using a package called react share and I have implemented it in another repository. 
- I would like to add it to this project.
- This would be a perfect addition to this project.

### Screenshots

image

### PR DESCRIPTION
**Pull request by saikiranreddy201**
# Pull Request Template

## Description

- Added share functionality on the profile page, where the user can share his profile with other apps.
- checked the code and its functionality

Fixes #235 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- I have tested by checking every app functionality in the modal card.

## Screenshots

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Arnabdaz** [comment]
LGTM :+1: nice work 

can you add this share modal to the polls sharing button also in the discover page

**Comment by saikiranreddy201** [comment]
Hey @Arnabdaz, yes I can add it, I’ll look into it and make necessary changes

**Comment by saikiranreddy201** [comment]
Hey @Arnabdaz there is no share button in the Discover page.

polls share button

Is this what you are talking about? Am I supposed to add it here?

**Comment by Arnabdaz** [comment]
> Hey @Arnabdaz there is no share button in the Discover page.
> 
> polls share button
> Is this what you are talking about? Am I supposed to add it here?

yes

**Comment by saikiranreddy201** [comment]
Hey @Arnabdaz, I have added the share functionality and removed a bug, **shown below.**

image

- Earlier we could not access the poll due to a blunder in the code, I have fixed it now.

**Sorry, the work has been delayed due to some personal work. Now can you Please review my pr?**

**Comment by saikiranreddy201** [comment]
**Associated screenshot**

image

**Example**: Sharing as a tweet on Twitter.

image

**Comment by saikiranreddy201** [comment]
Hey, @Arnabdaz. Could you please take a look at another issue I raised? :)  #258

**Review by Arnabdaz — APPROVED** [review]
LGTM 👍 Nice Work 🚀

**Pull request merged**
