### PR TITLE
Addition of auto-comment.yml file

### LINKED ISSUE #185: Addition of auto-comment.yml file
We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance

@agamjotsingh18  *Please assign me this issue under gssoc'23*

### PR DESCRIPTION
**Pull request by DivyanshiNarang**
# Pull Request Template

## Description

Added auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively.

Fixes #185 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by DivyanshiNarang** [comment]
@agamjotsingh18 Please review this PR.

**Comment by Arnabdaz** [comment]
@DivyanshiNarang  can you check it seems to be failing

**Comment by DivyanshiNarang** [comment]
Hello @Arnabdaz Please enable these permissions in order to make this workflow work as expected.

Screenshot 2023-07-03 234341

**Comment by DivyanshiNarang** [comment]
Hello @Arnabdaz @agamjotsingh18 Can you please review this PR?

**Pull request closed without merging**
